export const COMPONENTS = {
    DELETE: "delete",
    EDIT: "edit",
    EDIT_NOTE: "edit note",
    SUBMIT: "submit",
    SELECT_AN_OPTION: "select an option",
    VERY_IMPORTANT: "very important",
    IMPORTANT: "important",
    LESS_IMPORTANT: "less important",
    ERROR_DURING_REGISTRATION: "error during registration",
    EMAIL_AND_PASSWORD_IS_INCORRECT: "email and password is incorrect",
    PASSWORD_DOESNT_MEET_THE_REQUIREMENT: "password doesnt meet the requirement",
    NOTES: "notes",
    ADD_NOTES: "add notes",
    LOGOUT: "logout",
    LOGIN: "login",
    MANAGE: "manage",
    DELETE_ALL: "delete all",
    NO_DATA: "no data",
    FILTER: "filter",
    LOADING: 'loading...'
}